[package]
name = "steam-cdn"
version = "0.1.0"
edition = "2021"
description = "Steam CDN"
license = "Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs", "macros"] }
futures = "0.3"
steam-vent = "0.3"
serde = { version = "1.0", features = ["derive"] }
keyvalues-parser = "0.2"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
thiserror = "2.0"
zip = "2.2"
itertools = "0.14"
crc32fast = "1.4"
bytes = "1.9"
base64 = "0.22"
protobuf = "3.5"
aes = "0.8"
cbc = "0.1"
lzma-rs = { version = "0.3", features = ["raw_decoder"] }
